### ISSUE TITLE
Cannot find module 'mongoose'

### ISSUE THREAD

**Issue by felix0814** [vvpvvp/UMock#3]
node: v10.12.0
npm: 6.5.0
mac 

error info
Caught exception:
{ Error: Cannot find module 'mongoose'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.mockServer.initLocalServer (/Users/zhangshuai/app/umock/server/views/router.js:112:24)
    at Function.umock.init (/Users/zhangshuai/app/umock/server/umock.js:180:16)
    at Object.customRoute (/Users/zhangshuai/app/umock/server/init.js:55:23)
    at Object.init (/Users/zhangshuai/app/umock/server/init.js:17:14)
    at Object.<anonymous> (/Users/zhangshuai/app/umock/bin/umock:12:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30) code: 'MODULE_NOT_FOUND' }

不能跑起来？哪个地方做的不对吗？麻烦帮忙看一下～～～

**Comment by felix0814** [comment]
整明白了～
